### ISSUE TITLE
建议把所有资源文件全部改成本地，没必要用CDN

### ISSUE THREAD

**Issue by Kia678** [v03413/epay_usdt#10]
建议把所有资源文件全部改成本地，没必要用CDN
大家基本都是自建epay，本身就有服务器，没必要再套任何CDN
万一CDN挂了，还很麻烦

**Comment by kikij11** [comment]
define('PLUGIN_STATIC', 'https://cdn.vizan.cc/other/epay_usdt'); 这里要改成什么呢
