### ISSUE TITLE
这个版本的彩虹易支付能否出个usdt 支付插件？

### ISSUE THREAD

**Issue by Lins** [v03413/epay_usdt#2]
https://github.com/Blokura/Epay 

这个版本的彩虹易支付能否出个usdt 支付插件？

谢谢

**Comment by v03413** [comment]
> https://github.com/Blokura/Epay
> 
> 这个版本的彩虹易支付能否出个usdt 支付插件？
> 
> 谢谢

这个版本太老了，没有计划适配。

**Comment by heaid** [comment]
请问这个插件支持的是哪一版的彩虹易支付，我目前使用的 插件里导入后不显示 ，貌似还需要一个config.ini这个文件。

**Comment by mxw168** [comment]
> 

我现在也是这个问题，请问你的解决了吗

**Comment by mxw168** [comment]
> 请问这个插件支持的是哪一版的彩虹易支付，我目前使用的插件里导入后不显示，貌似还需要一个config.ini这个文件。

你弄好了没？
